DELIMITER $$

DROP TRIGGER GENERATE_EMPLOYEE_PASSWORD $$

CREATE TRIGGER GENERATE_EMPLOYEE_PASSWORD BEFORE INSERT ON employee 
    FOR EACH ROW BEGIN
           IF NEW.PASSWORD IS NULL THEN
               SET NEW.PASSWORD = CONCAT(SUBSTR(NEW.NAME,1,4),SUBSTR(NEW.CONTACT_NO,-4,4));
           END IF;
       END;
$$

DELIMITER ;